global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ledger'
    static_configs:
      - targets: ['ledger:8083']

  - job_name: 'payments'
    static_configs:
      - targets: ['payments:8082']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']

  - job_name: 'notifications'
    static_configs:
      - targets: ['notifications:8084']

  - job_name: 'fraud'
    static_configs:
      - targets: ['fraud:8081']

  - job_name: 'reconciler'
    static_configs:
      - targets: ['reconciler:8081']
